travis:
  secure:
    BINSTAR_TOKEN: BGxyy8N/B1Xdeqqs+7ZuEkW02PPYJSsxh3sgFgFE5zy5u6oMpr0jZTviEV8YXDVXupxI4S3mHNX2MOOvcI9K2miTj/mbEYy2I9kllQWwU7lwEOKULNeFdiAG0kSBerM1ng15cOZcoahUTkyPSGwro7WwHfS+Zb5oFpFQfn8Zh6StedoOwE9LZKh4lG9kXo0NC+Wao8rvezlUF4uNa3aO7F/nf6ir/NpTWmsuFxUmeNkGyIkoqIhDzmIAWYGnV9/tBwdNG1V4hng0BYVaZBnx4oho6wJ/Xhv7Q+Mg8O0SmTwnFA3r9/OkfzsQ4vBz8PcaRVWq/YmVFcj4Syb/wNttI2INOkZLhhjsc5VGQB0DS+ShzC9iDANVb/14B2X1A0KhHyN0fkhoMBmOVUE/t+ROQJscOSDbJ/ZgexrgKWRTSsmnsXDlHxg/XdMzOLxAUOzb7Mknv+DwUoJ8Y+RsC/Ly8y8PArjLDGnwEg0W6t0Bd2iTFipwzf5yVv8UmtEVdupsIE26/Rt1v9Gzc+p/LgtubED+4WA+T7nUeGOvWCOgYlLBIKP76zLoi9tU7F9xOgEEKNO2sj7q7oY49nM92jXtkF1SceqccV1a83qgC2tCcVioMm6YysgLBnnpIhRzr7pAyKMFzMZ2sl3w/BOST0M2x0negzJNT71ELP2AoofuriA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
