travis:
  secure:
    BINSTAR_TOKEN: cBaHvE5A/3IlrexMDOV5afY9dEFuaKhw43RtqB71BMiezlWMTxXgHPD33g0PKzY4LucNhztWS5EWl7tE6WVGHKMwuFvQNXIr91Pexj8BBQ+Hzb28AGctOpRx6llK1o4eOmzIkW/F23fZ7q9wBREEc5YuQ31PDl2RZSGuUcxfmISkKspEz8+oDYVbHiQPcxGnKRpywiAMH0JE0lrjZ+obrBEHcN6Id0bsDwFXMzbATwy4rpqVMrPjTzUEB0hKO0OFaQMolZmtvuvdss4NN7LjjnXI2hZHlVFwpT2H1Xka76qQcwAF9TKEIyE/7/NlKa068/76t6n4PsTOok7cSgX7iXfgmJxhWpc6vR9itd9fh8yEz8Qpao94PAnJ+h4XaROz0GS0bQFyZ3ghFhCb2fRMbzVuiOWtyNxBiviE7EFw5q2tHAFp4pXv6gHUgSf5gtYHa6UIpGAELDZDEu7VIzwgNm9mYRdnQVSmaoZR4LTjpqG8TilcGsE30EDT2v7ylQa78ogwQoBjCym6HJJkoiFjC//tsCwnVjLxJ8MQ1txhina2h9KJh2F148eg4F/wCZBgGCqj3ko1OVQWBREMBNo4PurrkYzhTbqyxv/Dh1HDTr9gzIlZOWcrZnI+ADKN9yFYnf7H48sG3y0OZipn0ZyZhXMm6Y29OjLIcAeoJTJbV0A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
