travis:
  secure:
    BINSTAR_TOKEN: tP2W1EHqaqMU70Uk8dhQHxN6KMc7aSBlkCG8f3aolCA0QMieTh7DOCE+ywux7aGIoZvGZ7y2Jfs+oXW7kv4qq3EF9ZfaQ/KdF7W33pGvTv0yng415bag4wwyOAwd+OqxY1zXyVcP6/eKKXur32PJiQdAzkCyfykOqszJOOmzD8Q0V9pTV2rxQXj00S8w6GJlpOVcmqjXGJml1zaCgG5yk1QN2ERHp0Zqo1hTJhBnDO0Pkxe4IsmntYM1WAVQVhycg5/QLsVI1I+MpXShIauIQEW1SIfJ3lJqdMxXglbBO5qYUp5EvUphwO6d6usBcT7lpF7E6BSRoGX/qe1bSs6KLcE7v2fye1UgTa+PVgrgkLOX9/Mn2uFuuoqcVQ6duxxo5kOTJpRiV59MkeaXWsfTV5ker5/q4VG/HqiJ4CUYxCPivTX0OKfk26DWOVIi+3Eis/Wnp7xHL022h06/p+CpJh9JB6tnCaY97fLc7V904kyG9xsZ04ox0CcBx13Wi1+A4tMtKjehz2mYrD2hsw/Vc5Gvs98SMEHqv0T/JhkDHY9tgSD3IXvEEw/B7XrFXD1UHLF13JxRJPBJ/0ViavpLi5xJYM9uYT1pM/p53BWObB9r6UeQEDAA3E8m4yi1Lb6tuMVlc5t3Bj0tiuqokaFcqxbjkN1qmbAM8N0wu/y3CwQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
